### PR TITLE
some small tidyups

### PR DESCRIPTION
**Pull request by marksmayo**
was just running pylint runner
 - cleaned up white space
- tidied imports with isort
 - ensured tests still pass

There's a lot more that can be done once 2.7 stops getting supported.

### CODE REVIEW

**Comment by alexmojaki** [comment]
Thanks! Not sure why you changed GHA to use tox, but it was working fine before and now it's not.

**Comment by marksmayo** [comment]
I'm not sure I even know how to change that - where was that change?

**Comment by marksmayo** [comment]
ok that must have been something in my environment auto-'fixing', let me sort.

**Comment by alexmojaki** [comment]
Something auto-fixed `.github/workflows/pytest.yml`?

**Comment by marksmayo** [comment]
Your commit a few minute later seems to have changed it?

image

**Comment by alexmojaki** [comment]
oh lol i used the web editor to change one line to `runs-on: ubuntu-20.04` and a browser extension to autofill the commit message and it must have also autofilled the file without me noticing. please do me a favour and change it back but keep that one line change.

**Comment by marksmayo** [comment]
done (fingers crossed)

**Comment by alexmojaki** [comment]
Thanks!

**Pull request merged**
